// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjXN9-w-El5IazksTSJr1qLNyXtA34ons',
    appId: '1:244222275646:web:3919f341eca3c04f00e16f',
    messagingSenderId: '244222275646',
    projectId: 'vibranium-hq',
    authDomain: 'vibranium-hq.firebaseapp.com',
    storageBucket: 'vibranium-hq.firebasestorage.app',
    measurementId: 'G-VMFR7L3TBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgtEGkCNM2VfTNkoeRY3Ik0ceTRYV2VQ8',
    appId: '1:244222275646:android:f66e711893d676d800e16f',
    messagingSenderId: '244222275646',
    projectId: 'vibranium-hq',
    storageBucket: 'vibranium-hq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDurQftr1Ljfeu6Tq7eK4uPO_EIMl4Tm-0',
    appId: '1:244222275646:ios:16d894c296b116c000e16f',
    messagingSenderId: '244222275646',
    projectId: 'vibranium-hq',
    storageBucket: 'vibranium-hq.firebasestorage.app',
    iosBundleId: 'com.example.soulspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDurQftr1Ljfeu6Tq7eK4uPO_EIMl4Tm-0',
    appId: '1:244222275646:ios:16d894c296b116c000e16f',
    messagingSenderId: '244222275646',
    projectId: 'vibranium-hq',
    storageBucket: 'vibranium-hq.firebasestorage.app',
    iosBundleId: 'com.example.soulspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjXN9-w-El5IazksTSJr1qLNyXtA34ons',
    appId: '1:244222275646:web:53cfd496607bed7100e16f',
    messagingSenderId: '244222275646',
    projectId: 'vibranium-hq',
    authDomain: 'vibranium-hq.firebaseapp.com',
    storageBucket: 'vibranium-hq.firebasestorage.app',
    measurementId: 'G-R7QYN5JBHG',
  );
}
